#!/bin/bash
IFS='
'
i=1
for url in $NAUTILUS_SCRIPT_SELECTED_URIS
do
	if [ -n "`echo $url | grep 'file:///'`" ];then
		gksu -m "输入你的密码执行管理权限的任务" gnome-open `echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | cut -f$i -d'
'` root &
	else
		gksu -m "输入你的密码执行管理权限的任务" gnome-open "$url" root &
	fi
	i=$(($i+1))
done
